name = "CitableCollection"
uuid = "7b95b006-44c5-4794-afff-00ccebff52d7"
authors = ["Neel Smith <dnsmith.neel@gmail.com>"]
version = "0.1.0"

[deps]
CitableBase = "d6f014bd-995c-41bd-9893-703339864534"
